/// Full crop database used for the Soil Analysis / Crop Advisor page.
/// Includes fruits, vegetables, grains, and legumes with ideal growing conditions.
library;

class CropInfo {
  final String id;
  final String name;
  final String emoji;
  final String category; // 'vegetable', 'fruit', 'grain', 'legume', 'spice'
  final String description;
  final List<String> tips;
  final List<String> benefits;

  // Ideal ranges
  final double tempMin, tempMax;
  final double humidityMin, humidityMax;
  final double nMin, nMax;
  final double pMin, pMax;
  final double kMin, kMax;
  final double phMin, phMax;
  final double rainfallMin, rainfallMax; // mm

  const CropInfo({
    required this.id,
    required this.name,
    required this.emoji,
    required this.category,
    required this.description,
    required this.tips,
    required this.benefits,
    required this.tempMin,
    required this.tempMax,
    required this.humidityMin,
    required this.humidityMax,
    required this.nMin,
    required this.nMax,
    required this.pMin,
    required this.pMax,
    required this.kMin,
    required this.kMax,
    required this.phMin,
    required this.phMax,
    required this.rainfallMin,
    required this.rainfallMax,
  });

  /// Score 0–100 based on how well given conditions match ideal ranges.
  double score({
    required double temperature,
    required double humidity,
    required double n,
    required double p,
    required double k,
    required double ph,
    double rainfall = 100,
  }) {
    double s = 0;
    s += _rangeScore(temperature, tempMin, tempMax) * 25;
    s += _rangeScore(humidity, humidityMin, humidityMax) * 15;
    s += _rangeScore(n, nMin, nMax) * 20;
    s += _rangeScore(p, pMin, pMax) * 15;
    s += _rangeScore(k, kMin, kMax) * 15;
    s += _rangeScore(ph, phMin, phMax) * 10;
    return s.clamp(0, 100);
  }

  static double _rangeScore(double val, double min, double max) {
    if (val >= min && val <= max) return 1.0;
    final mid = (min + max) / 2;
    final range = (max - min) / 2;
    final dist = (val - mid).abs() - range;
    return (1 - (dist / (range + 1)).clamp(0.0, 1.0));
  }

}

/// ─── Full crop database ───────────────────────────────────────────────────────
const List<CropInfo> cropDatabase = [
  // ── Grains ──
  CropInfo(
    id: 'rice',
    name: 'Rice',
    emoji: '🌾',
    category: 'grain',
    description: 'Staple cereal crop, thrives in waterlogged paddies.',
    tips: [
      'Maintain standing water 5–10 cm',
      'Transplant at 25–30 days',
      'Use split N fertilizer',
    ],
    benefits: [
      'High calorie staple',
      'Gluten-free',
      'Good carbohydrate source',
    ],
    tempMin: 20,
    tempMax: 35,
    humidityMin: 60,
    humidityMax: 90,
    nMin: 80,
    nMax: 140,
    pMin: 30,
    pMax: 60,
    kMin: 40,
    kMax: 80,
    phMin: 5.5,
    phMax: 7.0,
    rainfallMin: 150,
    rainfallMax: 300,
  ),
  CropInfo(
    id: 'maize',
    name: 'Maize / Corn',
    emoji: '🌽',
    category: 'grain',
    description: 'Versatile cereal crop used for food, feed, and biofuel.',
    tips: [
      'Plant in full sun',
      'Space rows 75 cm apart',
      'Water regularly during silking',
    ],
    benefits: ['High energy crop', 'Versatile uses', 'Fast growing'],
    tempMin: 18,
    tempMax: 32,
    humidityMin: 50,
    humidityMax: 75,
    nMin: 70,
    nMax: 120,
    pMin: 35,
    pMax: 65,
    kMin: 40,
    kMax: 80,
    phMin: 5.8,
    phMax: 7.0,
    rainfallMin: 75,
    rainfallMax: 200,
  ),
  CropInfo(
    id: 'wheat',
    name: 'Wheat',
    emoji: '🌾',
    category: 'grain',
    description: 'Cool-season cereal, basis of bread and pasta.',
    tips: [
      'Sow in cool season',
      'Avoid waterlogging',
      'Monitor for rust fungus',
    ],
    benefits: ['High protein grain', 'Global staple', 'Long shelf life'],
    tempMin: 12,
    tempMax: 25,
    humidityMin: 40,
    humidityMax: 65,
    nMin: 60,
    nMax: 100,
    pMin: 30,
    pMax: 55,
    kMin: 30,
    kMax: 60,
    phMin: 6.0,
    phMax: 7.5,
    rainfallMin: 50,
    rainfallMax: 120,
  ),

  // ── Legumes ──
  CropInfo(
    id: 'kidneybeans',
    name: 'Kidney Beans',
    emoji: '🫘',
    category: 'legume',
    description: 'Protein-rich legume popular in tropical climates.',
    tips: [
      'Do not over-water',
      'Inoculate seed with Rhizobium',
      'Harvest when pods dry',
    ],
    benefits: ['High protein', 'Fixes nitrogen in soil', 'Rich in fiber'],
    tempMin: 18,
    tempMax: 28,
    humidityMin: 45,
    humidityMax: 75,
    nMin: 20,
    nMax: 50,
    pMin: 40,
    pMax: 80,
    kMin: 20,
    kMax: 50,
    phMin: 6.0,
    phMax: 7.5,
    rainfallMin: 50,
    rainfallMax: 150,
  ),
  CropInfo(
    id: 'mungbean',
    name: 'Mung Bean',
    emoji: '🫘',
    category: 'legume',
    description: 'Fast-growing legume, popular across South & Southeast Asia.',
    tips: [
      'Short growing season (60–90 days)',
      'Well-drained sandy loam preferred',
      'Harvest early morning',
    ],
    benefits: [
      'Rich in protein and folate',
      'Improves soil health',
      'Low water requirement',
    ],
    tempMin: 22,
    tempMax: 32,
    humidityMin: 40,
    humidityMax: 70,
    nMin: 20,
    nMax: 45,
    pMin: 35,
    pMax: 65,
    kMin: 20,
    kMax: 45,
    phMin: 6.2,
    phMax: 7.2,
    rainfallMin: 60,
    rainfallMax: 150,
  ),
  CropInfo(
    id: 'chickpea',
    name: 'Chickpea',
    emoji: '🫘',
    category: 'legume',
    description: 'Drought-tolerant pulse crop, high in protein.',
    tips: [
      'Grows well in dry conditions',
      'Avoid excess nitrogen',
      'Cool temperatures preferred',
    ],
    benefits: [
      'Excellent protein source',
      'Drought tolerant',
      'Soil enriching',
    ],
    tempMin: 15,
    tempMax: 25,
    humidityMin: 20,
    humidityMax: 55,
    nMin: 20,
    nMax: 40,
    pMin: 40,
    pMax: 75,
    kMin: 20,
    kMax: 45,
    phMin: 6.0,
    phMax: 8.0,
    rainfallMin: 30,
    rainfallMax: 100,
  ),
  CropInfo(
    id: 'lentil',
    name: 'Lentil',
    emoji: '🫘',
    category: 'legume',
    description: 'Hardy, fast-maturing legume for cooler climates.',
    tips: [
      'Plant in light, free-draining soil',
      'Minimal fertilizer needed',
      'Harvest when lower pods brown',
    ],
    benefits: ['High iron and protein', 'Low water use', 'Soil nitrogen fixer'],
    tempMin: 12,
    tempMax: 24,
    humidityMin: 30,
    humidityMax: 60,
    nMin: 15,
    nMax: 40,
    pMin: 25,
    pMax: 55,
    kMin: 20,
    kMax: 45,
    phMin: 6.0,
    phMax: 8.0,
    rainfallMin: 30,
    rainfallMax: 90,
  ),

  // ── Vegetables ──
  CropInfo(
    id: 'tomato',
    name: 'Tomato',
    emoji: '🍅',
    category: 'vegetable',
    description: 'Warm-season fruiting vegetable, rich in lycopene.',
    tips: [
      'Support with stakes or cages',
      'Consistent watering prevents blossom end rot',
      'Prune suckers for bigger fruit',
    ],
    benefits: [
      'Rich in vitamins C & K',
      'Antioxidant lycopene',
      'Versatile culinary use',
    ],
    tempMin: 18,
    tempMax: 30,
    humidityMin: 50,
    humidityMax: 75,
    nMin: 60,
    nMax: 100,
    pMin: 40,
    pMax: 70,
    kMin: 50,
    kMax: 90,
    phMin: 6.0,
    phMax: 7.0,
    rainfallMin: 60,
    rainfallMax: 150,
  ),
  CropInfo(
    id: 'potato',
    name: 'Potato',
    emoji: '🥔',
    category: 'vegetable',
    description: 'Cool-season tuber crop, globally important staple.',
    tips: [
      'Plant seed potatoes 10 cm deep',
      'Hill soil as plants grow',
      'Harvest after foliage dies back',
    ],
    benefits: [
      'High in potassium',
      'Energy-dense staple',
      'High yield per area',
    ],
    tempMin: 10,
    tempMax: 22,
    humidityMin: 55,
    humidityMax: 80,
    nMin: 80,
    nMax: 130,
    pMin: 50,
    pMax: 80,
    kMin: 70,
    kMax: 120,
    phMin: 4.8,
    phMax: 6.5,
    rainfallMin: 70,
    rainfallMax: 150,
  ),
  CropInfo(
    id: 'onion',
    name: 'Onion',
    emoji: '🧅',
    category: 'vegetable',
    description: 'Pungent bulb vegetable with global culinary importance.',
    tips: [
      'Plant sets or transplants in spring',
      'Keep weed-free',
      'Cure bulbs before storage',
    ],
    benefits: [
      'Rich in quercetin antioxidant',
      'Immune support',
      'Long storage life',
    ],
    tempMin: 13,
    tempMax: 24,
    humidityMin: 55,
    humidityMax: 75,
    nMin: 50,
    nMax: 90,
    pMin: 30,
    pMax: 60,
    kMin: 50,
    kMax: 90,
    phMin: 6.0,
    phMax: 7.0,
    rainfallMin: 50,
    rainfallMax: 120,
  ),
  CropInfo(
    id: 'cabbage',
    name: 'Cabbage',
    emoji: '🥬',
    category: 'vegetable',
    description: 'Cool-season leafy vegetable packed with vitamins.',
    tips: [
      'Firm up heads with consistent watering',
      'Watch for caterpillars',
      'Harvest before cracking',
    ],
    benefits: [
      'High in vitamin C & K',
      'Anti-inflammatory',
      'Excellent for coleslaw & fermentation',
    ],
    tempMin: 7,
    tempMax: 22,
    humidityMin: 60,
    humidityMax: 80,
    nMin: 60,
    nMax: 100,
    pMin: 30,
    pMax: 60,
    kMin: 50,
    kMax: 90,
    phMin: 6.0,
    phMax: 7.5,
    rainfallMin: 60,
    rainfallMax: 150,
  ),
  CropInfo(
    id: 'carrot',
    name: 'Carrot',
    emoji: '🥕',
    category: 'vegetable',
    description: 'Root vegetable rich in beta-carotene, prefers loose soil.',
    tips: [
      'Deep, loose, stone-free soil',
      'Thin seedlings to 5cm apart',
      'Avoid high nitrogen for sweet roots',
    ],
    benefits: [
      'Excellent source of vitamin A',
      'Improves night vision',
      'High fiber content',
    ],
    tempMin: 10,
    tempMax: 22,
    humidityMin: 50,
    humidityMax: 75,
    nMin: 30,
    nMax: 60,
    pMin: 40,
    pMax: 70,
    kMin: 60,
    kMax: 100,
    phMin: 6.0,
    phMax: 7.0,
    rainfallMin: 40,
    rainfallMax: 100,
  ),
  CropInfo(
    id: 'chili',
    name: 'Chili Pepper',
    emoji: '🌶️',
    category: 'vegetable',
    description: 'Warm-season pepper with high capsaicin content.',
    tips: [
      'Full sun location',
      'Water during fruit set',
      'Harvest regularly for continued production',
    ],
    benefits: [
      'Rich in capsaicin (metabolism boost)',
      'High vitamin C',
      'Antioxidant properties',
    ],
    tempMin: 20,
    tempMax: 35,
    humidityMin: 50,
    humidityMax: 75,
    nMin: 50,
    nMax: 90,
    pMin: 30,
    pMax: 60,
    kMin: 50,
    kMax: 80,
    phMin: 6.0,
    phMax: 7.0,
    rainfallMin: 60,
    rainfallMax: 150,
  ),
  CropInfo(
    id: 'spinach',
    name: 'Spinach',
    emoji: '🥬',
    category: 'vegetable',
    description: 'Fast-growing leafy green, rich in iron and vitamins.',
    tips: [
      'Grow in cool weather',
      'Harvest outer leaves first',
      'Bolt-resistant varieties for summer',
    ],
    benefits: [
      'Excellent iron & folate source',
      'Rich in vitamin K',
      'Quick growing',
    ],
    tempMin: 5,
    tempMax: 20,
    humidityMin: 55,
    humidityMax: 80,
    nMin: 50,
    nMax: 90,
    pMin: 25,
    pMax: 50,
    kMin: 40,
    kMax: 75,
    phMin: 6.0,
    phMax: 7.5,
    rainfallMin: 40,
    rainfallMax: 100,
  ),
  CropInfo(
    id: 'cucumber',
    name: 'Cucumber',
    emoji: '🥒',
    category: 'vegetable',
    description: 'Warm-season vine crop with high water content.',
    tips: [
      'Trellis for better air circulation',
      'Harvest frequently while young',
      'Keep soil consistently moist',
    ],
    benefits: [
      'High hydration crop',
      'Contains vitamin K',
      'Very fast growing',
    ],
    tempMin: 20,
    tempMax: 35,
    humidityMin: 60,
    humidityMax: 85,
    nMin: 50,
    nMax: 90,
    pMin: 30,
    pMax: 60,
    kMin: 50,
    kMax: 90,
    phMin: 6.0,
    phMax: 7.0,
    rainfallMin: 80,
    rainfallMax: 200,
  ),
  CropInfo(
    id: 'eggplant',
    name: 'Eggplant / Brinjal',
    emoji: '🍆',
    category: 'vegetable',
    description: 'Heat-loving fruiting vegetable popular across Asia.',
    tips: ['Long growing season', 'Stake tall varieties', 'Protect from frost'],
    benefits: ['Rich in anthocyanins', 'Supports heart health', 'Low calorie'],
    tempMin: 22,
    tempMax: 35,
    humidityMin: 55,
    humidityMax: 80,
    nMin: 50,
    nMax: 90,
    pMin: 35,
    pMax: 65,
    kMin: 50,
    kMax: 85,
    phMin: 5.5,
    phMax: 7.0,
    rainfallMin: 60,
    rainfallMax: 150,
  ),
  CropInfo(
    id: 'pumpkin',
    name: 'Pumpkin',
    emoji: '🎃',
    category: 'vegetable',
    description: 'Large vine crop, nutritious and easy to store.',
    tips: [
      'Needs large space',
      'Pollinate by hand if needed',
      'Water at base, not leaves',
    ],
    benefits: ['Rich in beta-carotene', 'High fiber', 'Excellent storage life'],
    tempMin: 18,
    tempMax: 32,
    humidityMin: 50,
    humidityMax: 75,
    nMin: 40,
    nMax: 80,
    pMin: 35,
    pMax: 65,
    kMin: 50,
    kMax: 90,
    phMin: 6.0,
    phMax: 7.5,
    rainfallMin: 70,
    rainfallMax: 200,
  ),

  // ── Fruits ──
  CropInfo(
    id: 'mango',
    name: 'Mango',
    emoji: '🥭',
    category: 'fruit',
    description: 'Tropical king of fruits, requires dry season to flower.',
    tips: [
      'Allow dry period before flowering',
      'Grafted trees fruit earlier',
      'Prune after harvest',
    ],
    benefits: [
      'Extremely high in vitamin C',
      'Rich in antioxidants',
      'High market value',
    ],
    tempMin: 24,
    tempMax: 38,
    humidityMin: 40,
    humidityMax: 70,
    nMin: 30,
    nMax: 70,
    pMin: 20,
    pMax: 50,
    kMin: 50,
    kMax: 100,
    phMin: 5.5,
    phMax: 7.5,
    rainfallMin: 100,
    rainfallMax: 250,
  ),
  CropInfo(
    id: 'banana',
    name: 'Banana',
    emoji: '🍌',
    category: 'fruit',
    description: 'Fast-growing tropical fruit, continuous harvest.',
    tips: [
      'Requires lots of water',
      'Wind protection needed',
      'Remove suckers to 1–2 per plant',
    ],
    benefits: [
      'Excellent potassium source',
      'Quick energy',
      'Year-round production',
    ],
    tempMin: 22,
    tempMax: 38,
    humidityMin: 65,
    humidityMax: 90,
    nMin: 70,
    nMax: 120,
    pMin: 30,
    pMax: 60,
    kMin: 80,
    kMax: 140,
    phMin: 5.5,
    phMax: 7.0,
    rainfallMin: 150,
    rainfallMax: 350,
  ),
  CropInfo(
    id: 'papaya',
    name: 'Papaya',
    emoji: '🍈',
    category: 'fruit',
    description: 'Fast-fruiting tropical papaya, rich in papain enzyme.',
    tips: [
      'Plant on raised beds',
      'Avoid waterlogging',
      'Fruits in 6–10 months from seed',
    ],
    benefits: [
      'Contains papain enzyme',
      'Excellent vitamin C & A',
      'Fast return on investment',
    ],
    tempMin: 22,
    tempMax: 36,
    humidityMin: 55,
    humidityMax: 80,
    nMin: 50,
    nMax: 90,
    pMin: 30,
    pMax: 60,
    kMin: 60,
    kMax: 100,
    phMin: 6.0,
    phMax: 7.0,
    rainfallMin: 100,
    rainfallMax: 250,
  ),
  CropInfo(
    id: 'watermelon',
    name: 'Watermelon',
    emoji: '🍉',
    category: 'fruit',
    description: 'Heat-loving large vine fruit with high water content.',
    tips: [
      'Needs full sun and warm temps',
      'Reduce water near harvest',
      'Thump test for ripeness',
    ],
    benefits: [
      '95% water content',
      'Rich in lycopene',
      'Excellent hot-weather crop',
    ],
    tempMin: 24,
    tempMax: 36,
    humidityMin: 40,
    humidityMax: 65,
    nMin: 40,
    nMax: 80,
    pMin: 30,
    pMax: 60,
    kMin: 50,
    kMax: 100,
    phMin: 6.0,
    phMax: 7.0,
    rainfallMin: 60,
    rainfallMax: 150,
  ),
  CropInfo(
    id: 'pineapple',
    name: 'Pineapple',
    emoji: '🍍',
    category: 'fruit',
    description: 'Tropical bromeliad adapted to well-drained acidic soils.',
    tips: [
      'Plant crowns or ratoon suckers',
      'Very drought tolerant once established',
      'Ethylene treatment speeds flowering',
    ],
    benefits: [
      'Contains bromelain enzyme',
      'High vitamin C',
      'Good export value',
    ],
    tempMin: 20,
    tempMax: 35,
    humidityMin: 45,
    humidityMax: 70,
    nMin: 40,
    nMax: 80,
    pMin: 20,
    pMax: 50,
    kMin: 60,
    kMax: 100,
    phMin: 4.5,
    phMax: 6.5,
    rainfallMin: 100,
    rainfallMax: 250,
  ),
  CropInfo(
    id: 'grapes',
    name: 'Grapes',
    emoji: '🍇',
    category: 'fruit',
    description: 'Perennial vine crop, requires trellis and annual pruning.',
    tips: [
      'Train on trellis system',
      'Dormant pruning is critical',
      'Reduce irrigation at harvest',
    ],
    benefits: [
      'Rich in resveratrol',
      'High market value',
      'Long productive lifespan',
    ],
    tempMin: 15,
    tempMax: 30,
    humidityMin: 40,
    humidityMax: 65,
    nMin: 30,
    nMax: 60,
    pMin: 20,
    pMax: 50,
    kMin: 60,
    kMax: 100,
    phMin: 5.5,
    phMax: 7.0,
    rainfallMin: 60,
    rainfallMax: 150,
  ),
  CropInfo(
    id: 'strawberry',
    name: 'Strawberry',
    emoji: '🍓',
    category: 'fruit',
    description: 'Cool-season berry with high demand and market value.',
    tips: [
      'Raised beds improve drainage',
      'Mulch to keep fruit clean',
      'Remove runners for larger fruit',
    ],
    benefits: [
      'Very high vitamin C',
      'Premium market price',
      'Quick to first harvest',
    ],
    tempMin: 10,
    tempMax: 22,
    humidityMin: 60,
    humidityMax: 80,
    nMin: 40,
    nMax: 70,
    pMin: 35,
    pMax: 65,
    kMin: 50,
    kMax: 85,
    phMin: 5.5,
    phMax: 7.0,
    rainfallMin: 60,
    rainfallMax: 150,
  ),
  CropInfo(
    id: 'lemon',
    name: 'Lemon / Lime',
    emoji: '🍋',
    category: 'fruit',
    description: 'Citrus fruit adapted to tropical and subtropical climates.',
    tips: [
      'Well-drained soil essential',
      'Regular fertilization',
      'Protect from frost',
    ],
    benefits: [
      'Rich in vitamin C',
      'High demand',
      'Can intercrop with other crops',
    ],
    tempMin: 20,
    tempMax: 35,
    humidityMin: 45,
    humidityMax: 70,
    nMin: 40,
    nMax: 80,
    pMin: 20,
    pMax: 50,
    kMin: 50,
    kMax: 90,
    phMin: 5.5,
    phMax: 7.0,
    rainfallMin: 100,
    rainfallMax: 200,
  ),

  // ── Spices / Herbs ──
  CropInfo(
    id: 'ginger',
    name: 'Ginger',
    emoji: '🫚',
    category: 'spice',
    description: 'Rhizome spice crop requiring partial shade and moisture.',
    tips: [
      'Plant in filtered sunlight',
      'Moist but well-drained soil',
      'Harvest 8–10 months after planting',
    ],
    benefits: [
      'Medicinal and culinary uses',
      'High market value',
      'Low pest pressure',
    ],
    tempMin: 20,
    tempMax: 32,
    humidityMin: 65,
    humidityMax: 85,
    nMin: 40,
    nMax: 80,
    pMin: 30,
    pMax: 60,
    kMin: 50,
    kMax: 90,
    phMin: 5.5,
    phMax: 7.0,
    rainfallMin: 120,
    rainfallMax: 250,
  ),
  CropInfo(
    id: 'turmeric',
    name: 'Turmeric',
    emoji: '🟡',
    category: 'spice',
    description:
        'Tropical rhizome spice with powerful anti-inflammatory properties.',
    tips: [
      'Plant rhizomes shallow',
      'Heavy mulching improves yield',
      'Harvest 7–10 months after planting',
    ],
    benefits: [
      'Anti-inflammatory curcumin',
      'Natural dye',
      'High export value',
    ],
    tempMin: 20,
    tempMax: 35,
    humidityMin: 65,
    humidityMax: 90,
    nMin: 40,
    nMax: 80,
    pMin: 30,
    pMax: 55,
    kMin: 50,
    kMax: 90,
    phMin: 5.5,
    phMax: 7.0,
    rainfallMin: 120,
    rainfallMax: 250,
  ),
  CropInfo(
    id: 'garlic',
    name: 'Garlic',
    emoji: '🧄',
    category: 'spice',
    description: 'Cool-season bulb with strong antimicrobial properties.',
    tips: [
      'Plant cloves point up',
      'Remove scapes for larger bulbs',
      'Reduce water before harvest',
    ],
    benefits: [
      'Powerful antimicrobial',
      'Immune system support',
      'Long shelf life',
    ],
    tempMin: 10,
    tempMax: 22,
    humidityMin: 45,
    humidityMax: 70,
    nMin: 50,
    nMax: 90,
    pMin: 30,
    pMax: 60,
    kMin: 50,
    kMax: 90,
    phMin: 6.0,
    phMax: 7.5,
    rainfallMin: 40,
    rainfallMax: 100,
  ),
];
